[package]
name = "cruel_ruin_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
trust-dns-resolver = "0.20.3"

[lib]
crate-type = ["staticlib"]
